[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.25"

remappings = [
    "@fhevm/=lib/fhevm-solidity/"
]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"

[profile.default.fuzz]
runs = 256